root: true

env:
    node: true

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  no-console: 0
